import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import { addPerformer } from './add-performer.js';
import { init } from './init.js';

/**
 * 専用CLIの入口(ADR-0036)
 *
 * ファイル入出力とwranglerの実行は`CliDeps`で受け取る
 * 単体テストはメモリ実装へ差し替え, 実際の書き込みや子プロセスを伴わずに検査する
 */

export type CliFs = {
	exists(path: string): boolean;
	read(path: string): string;
	write(path: string, content: string): void;
	/** 再帰的に作る, 既存なら何もしない */
	mkdir(path: string): void;
};

/** 子プロセスの結果, 失敗もthrowせず値で返す */
export type RunResult = { ok: boolean; stdout: string; stderr: string };

export type CliDeps = {
	fs: CliFs;
	/** wranglerの実行, 実体は`npx wrangler`のspawnSync */
	wrangler(args: readonly string[]): RunResult;
	log(line: string): void;
	error(line: string): void;
	/** 生成パスの基点 */
	cwd: string;
	/** `--version`が出す文字列 */
	version: string;
	/** 対話モードへ入れるか, パイプ実行では入らない */
	isTty: boolean;
};

const USAGE = `usage: tsumugi <command> [options]

commands:
  init                    set up tsumugi in the current project
  add-performer <NAME>    generate a performer and export it from the barrel

options:
  --name <name>           worker name used by init (default: detected)
  --format <jsonc|toml>   config format generated by init (default: jsonc)
  --help                  show this message
  --version               show the version`;

const OPTIONS = {
	help: { type: 'boolean' },
	version: { type: 'boolean' },
	name: { type: 'string' },
	format: { type: 'string' },
} as const;

/** 引数を解釈してコマンドへ振り分ける, テストはここを入口にする */
export function main(argv: readonly string[], deps: CliDeps): number {
	let parsed: { values: { help?: boolean; version?: boolean; name?: string; format?: string }; positionals: string[] };
	try {
		parsed = parseArgs({ args: [...argv], options: OPTIONS, allowPositionals: true, strict: true });
	} catch (cause) {
		deps.error(`tsumugi: ${cause instanceof Error ? cause.message : String(cause)}`);
		deps.error(USAGE);
		return 1;
	}

	if (parsed.values.help) {
		deps.log(USAGE);
		return 0;
	}
	if (parsed.values.version) {
		deps.log(deps.version);
		return 0;
	}

	const [command, ...rest] = parsed.positionals;
	if (command === undefined) {
		deps.error(USAGE);
		return 1;
	}
	if (command === 'init') {
		const format = parsed.values.format ?? 'jsonc';
		if (format !== 'jsonc' && format !== 'toml') {
			deps.error(`tsumugi: unknown format "${format}", use jsonc or toml`);
			return 1;
		}
		return init({ name: parsed.values.name, format }, deps);
	}
	if (command === 'add-performer') {
		const name = rest[0];
		if (name === undefined) {
			deps.error('tsumugi: add-performer requires a name, e.g. `tsumugi add-performer send-mail`');
			return 1;
		}
		return addPerformer(name, deps);
	}

	deps.error(`tsumugi: unknown command "${command}"`);
	deps.error(USAGE);
	return 1;
}

/** バンドル後は`dist/cli.js`からパッケージルートのpackage.jsonを指す */
const packageVersion = (): string => {
	try {
		// workers-typesのURL型と衝突するので, URLオブジェクトを経由せず文字列で解決する
		const path = join(dirname(fileURLToPath(import.meta.url)), '..', 'package.json');
		const parsed = JSON.parse(readFileSync(path, 'utf8')) as { version?: string };
		return parsed.version ?? 'unknown';
	} catch {
		return 'unknown';
	}
};

const nodeDeps = (): CliDeps => ({
	fs: {
		exists: (path) => existsSync(path),
		read: (path) => readFileSync(path, 'utf8'),
		write: (path, content) => writeFileSync(path, content),
		mkdir: (path) => void mkdirSync(path, { recursive: true }),
	},
	wrangler: (args) => {
		const result = spawnSync('npx', ['wrangler', ...args], { encoding: 'utf8' });
		return { ok: result.status === 0 && result.error === undefined, stdout: result.stdout ?? '', stderr: result.stderr ?? '' };
	},
	log: (line) => console.log(line),
	error: (line) => console.error(line),
	cwd: process.cwd(),
	version: packageVersion(),
	isTty: process.stdin.isTTY === true && process.stdout.isTTY === true,
});

/** binの入口, 予期しない例外もexit codeへ丸める */
export function runCli(argv: readonly string[]): number {
	try {
		return main(argv, nodeDeps());
	} catch (cause) {
		console.error(`tsumugi: ${cause instanceof Error ? cause.message : String(cause)}`);
		return 1;
	}
}
